Sanjeeb.Interview.Web/ViewModels/ViewModelBooking.cs
using GroundControl.Interview.SeniorDeveloper.Model;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Sanjeeb.Interview.Web.ViewModels
{
    public class ViewModelBooking
    {
        protected IEnumerable<BookingType> _bookingTypes;
        protected int _bookingTypeId;
        public int bookingTypeId
        {
            get { return _bookingTypeId; }
            set { _bookingTypeId = value; }
        }
        public List<SelectListItem> SelectedListBookingTypes { get; set; }
        
        public IEnumerable<BookingType> BookingTypes
        {
            get { return _bookingTypes; }
            set { _bookingTypes = value;
          
                foreach (var bt in _bookingTypes)
                {
                    if (SelectedListBookingTypes == null)
                        SelectedListBookingTypes = new List<SelectListItem>();
                    
                    SelectedListBookingTypes.Add(new SelectListItem(bt.Name, bt.TypeId.ToString()));
                     
                }
            }
        }

        protected IEnumerable<VehicleMake> _vehicleMakes;
        protected int _vehicleMakeId;
        public int VehicleMakeId
        {
            get { return _vehicleMakeId; }
            set { _vehicleMakeId = value; }
        }
       
        public List<SelectListItem> SelectedListVehicleMakes { get; set; }
        public IEnumerable<VehicleMake> VehicleMakes
        {
            get { return _vehicleMakes; }
            set
            {
                _vehicleMakes = value;
                foreach(var bt in _vehicleMakes)
                {
                    if (SelectedListVehicleMakes == null)
                        SelectedListVehicleMakes = new List<SelectListItem>();

                    SelectedListVehicleMakes.Add(new SelectListItem(bt.Make, bt.MakeId.ToString()));
                }
            }
        }


        protected IEnumerable<VehicleModel> _vehicleModels;
        public int VehicleModelId { get; set; }
        public List<SelectListItem> SelectedListVehicleModels { get; set; }

        public IEnumerable<VehicleModel> VehicleModels
        {
            get { return _vehicleModels; }
            set { _vehicleModels = value; 
                foreach(var bt in _vehicleModels)
                {
                    if (SelectedListVehicleModels == null)
                        SelectedListVehicleModels = new List<SelectListItem>();

                    SelectedListVehicleModels.Add(new SelectListItem(bt.Model, bt.ModelId.ToString()));
                }
            }
        }
        
        [Required]
        [MaxLength(8,ErrorMessage ="Registration Number cannot exceed more than 8 caracters.")]
        [MinLength(7, ErrorMessage = "Registration Number cannot be less than 6 caracters.")]
        public string RegistrationNumber { get; set; }
       
        
        
    }
}

Sanjeeb.Interview.Web/Controllers/BookingController.cs
using GroundControl.Interview.SeniorDeveloper.Model;
using Microsoft.AspNetCore.Mvc;
using Sanjeeb.Interview.Web.Services;
using Sanjeeb.Interview.Web.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Sanjeeb.Interview.Web.Controllers
{
    [Route("[controller]")]
    public class BookingController : Controller
    {
        private readonly IGarageServices garageServices;
        public ViewModelBooking _viewModelBooking;

        public BookingController(IGarageServices garageServices)
        {
            this.garageServices = garageServices;
        }

        
        public async Task<IActionResult> Index()
        {
            if (_viewModelBooking == null)
                _viewModelBooking = new ViewModelBooking();
            _viewModelBooking.BookingTypes = (await garageServices.GetBookingTypes()).ToList();
            _viewModelBooking.VehicleMakes = (await garageServices.GetVehicleMakes()).ToList();

            return View(_viewModelBooking);
        }
        [Route("BookingList")]
        public async Task<IActionResult> BookingList()
        {
            var result = (await garageServices.GetBookings()).ToList();

            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Index(ViewModelBooking viewModelBooking)
        {
            var valid =true;
            if ((viewModelBooking.VehicleModelId < 0) ||
                (viewModelBooking.VehicleMakeId < 0) ||
                (string.IsNullOrEmpty(viewModelBooking.RegistrationNumber)) ||
                (viewModelBooking.bookingTypeId < 0))
                valid = false;

            if (valid)
            {
                var saveBooking = (await garageServices.SaveBookings(
                                            viewModelBooking.bookingTypeId, 
                                            viewModelBooking.VehicleMakeId,
                                            viewModelBooking.VehicleModelId,                                            
                                            viewModelBooking.RegistrationNumber));
                return RedirectToAction("BookingList");
            }
            viewModelBooking.BookingTypes= (await garageServices.GetBookingTypes()).ToList();
            return View(viewModelBooking);
        }
        

        [Route("GetVehicleMakes")]
        public async Task<JsonResult> GetVehicleMakes()
        {
            var result = await garageServices.GetVehicleMakes();
           return Json(result);            
        }

        [HttpPost]
    [Route("GetVehicleModels")]
        public async Task<JsonResult> GetVehicleModels(int makeid)
        {
            var result = await garageServices.GetVehicleModelsByMakeId(makeid);
           return Json(result);            
        }
    }
}

Sanjeeb.Interview.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Sanjeeb.Interview.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Sanjeeb.Interview.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
 
using Sanjeeb.Interview.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sanjeeb.Interview.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        
        public ViewModelBooking _viewModelBooking;
 
         

        public void OnGet()
        {

        }        
    }
}

Sanjeeb.Interview.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sanjeeb.Interview.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Sanjeeb.Interview.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Ground Control Interview: Sanjeeb's Solution.</p>
</div>

Sanjeeb.Interview.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sanjeeb.Interview.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Sanjeeb.Interview.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Booking" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sanjeeb.Interview.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Sanjeeb.Interview.Web/Views/Booking/BookingList.cshtml
@model IEnumerable<GroundControl.Interview.SeniorDeveloper.Model.Booking>

@{
    ViewData["Title"] = "BookingList";
}

<h1>BookingList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Registration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookingTypeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleModelId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Registration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleModelId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Sanjeeb.Interview.Web/Views/Booking/Index.cshtml
@model Sanjeeb.Interview.Web.ViewModels.ViewModelBooking

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    <h4>Select Bookings</h4>

    <div class="jumbotron">

        <form asp-controller="Booking" asp-action="Index" method="post" role="form">
            <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="BookingTypes" class="control-label"></label>
                <input type="hidden" name="bookingTypeId" id="bookingTypeId" value="" />
                <select name="BookingType" id="BookingType" class="form-control" asp-items="@(Model.SelectedListBookingTypes)">
                    <option value="-1">Please select one</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="VehicleMakes" class="control-label"></label>
                <input type="hidden" name="VehicleMakeId" id="VehicleMakeId" value="" />
                <select name="VehicleMakes" id="VehicleMakes" class="form-control" asp-items="@(Model.SelectedListVehicleMakes)">
                    <option value="-1">Please select one</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="VehicleModels" class="control-label"></label>
                <input type="hidden" name="VehicleModelId" id="VehicleModelId" value="" />
                <select id="VehicleModels" class="form-control" asp-items="@(Model.SelectedListVehicleModels)">
                    <option value="-1">Please select one</option>
                </select>
                 
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>

                <input name="RegistrationNumber" id="RegistrationNumber" class="form-control" asp-for="RegistrationNumber"  />
                  
                 <span asp-validation-for="RegistrationNumber"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="submitbtn" value="Book Service" onclick="checkValues()" class="btn btn-primary" />
            </div>
        </form>
    </div>
     
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
<script>
    function checkValues() {
        var VehicleModelId = $("#VehicleModels").val();
        $("#VehicleModelId").val(VehicleModelId);

        var VehicleMakeId = $("#VehicleMakes").val();
        $("#VehicleMakeId").val(VehicleMakeId);

        var bookingTypeId = $("#BookingType").val();
        $("#bookingTypeId").val(bookingTypeId);
        debugger;

    }
    $(function () {
        $('#VehicleMakes').prop('disabled', 'true');
        $('#submitbtn').prop('disabled', 'true');
        $('#VehicleModels').prop('disabled', 'true');
        $("#BookingType").change(function () {
            var BookingID = $("#BookingType").val();

            if (BookingID == -1) {
                $("#VehicleMakes").prop('selectedIndex', 0);
                $('#VehicleMakes').empty().append('<option value="-1">Please select one</option>');
                $('#VehicleMakes').prop('disabled', 'true');

                $('#VehicleModels').prop('disabled', 'true');
            }
            else {
                var url = '@Url.Action("GetVehicleMakes","Booking")';
                $('#VehicleMakes').removeAttr('disabled');
                $('#VehicleMakes').empty().append('<option value="-1">Please select one</option>');
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        $(data).each(function (index, returnitem) {
                            $('#VehicleMakes').append('<option value="' + returnitem.makeId+'">'+ returnitem.make+'</option>');
                             
                        });
                    }

                });
            }


        });

        $("#VehicleMakes").change(function () {
            var VehicleMakesID = $("#VehicleMakes").val();
            console.log(VehicleMakesID);
            if (VehicleMakesID == -1) {
                $("#VehicleModels").prop('selectedIndex', 0);
                $('#VehicleModels').empty().append('<option value="-1">Please select one</option>');
                $('#VehicleModels').prop('disabled', 'true');

                $('#VehicleModels').prop('disabled', 'true');
            }
            else {
                var url = '@Url.Action("GetVehicleModels","Booking")';
                $('#VehicleModels').removeAttr('disabled');
                $('#VehicleModels').empty().append('<option value="-1">Please select one</option>');
                
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {makeid:VehicleMakesID},
                    dataType: 'json',
                    success: function (data) {
                        if (data.length==0) {
                            $("#VehicleModels").prop('selectedIndex', 0);
                            $('#VehicleModels').empty().append('<option value="-1">Please select one</option>');
                            $('#VehicleModels').prop('disabled', 'true');

                            $('#VehicleModels').prop('disabled', 'true');
                        }
                        $(data).each(function (index, returnitem) {
                            $('#VehicleModels').append('<option value="' + returnitem.modelId+'">'+ returnitem.model+'</option>');
                            console.log(returnitem);
                        });
                    }
                });
            }
        });

        $("#VehicleModels").change(function () {
            if (checkValues() < 0) {
                $('#submitbtn').prop('disabled', 'true');
            } else {
                $('#submitbtn').removeAttr('disabled');
            }

        });
    });
</script>

Sanjeeb.Interview.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sanjeeb.Interview.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Sanjeeb.Interview.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Booking" asp-action="Index">Start Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Booking" asp-action="BookingList">Booking List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sanjeeb.Interview.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>